travis:
  secure:
    BINSTAR_TOKEN: LtIv7/hvILdjEp/gR9W1X5kGfgojcOqGA/Qzpqy8Ne6MDBFoSJYPaM/xIcu8Zzhci1PSrKutpximIxcu3TfG9Y8sUkDSINcpUH6KNhlfhhYiOp4fIc2Z8Gv1c8tzuGAuoDhYX2SZHYCscgePmN3JMV8WWDUaVs675D9NzEGjsyURnTzUfmf/5dCDs6+a5mHhDy19JOUJds3IerleeV/xCuDm0B6Ksbp3xqNFE+VgMgtr0BvoqK7nd8LnyfdJO2ymC9ByOtH9rDUrtQAwesXvNtWzVXAqMj3/N7cBSu8krh5B17U+n65afJh+34T9EDaUwp10NvqiVcXlerLEfW1yvxGhtowAsIoi2K9op7Fa3OTZfYiV9ZTQh2LlDD01dLzw+r/EvHH3wqzK0neWcO8Ezn2KurxgRosvqKGXUOk2Wls3krECX+Bkq/DeIN9K48wx/Obgv4W+Oob3NM4grpcFF3Pky/UQm6/TlY06U30VHhxuEUImbuH/14F0TnHRn5RE0e0TZdrhPjvMj6xnO+zfByUsn+BeTKVKN9+d5uzcPqpKcLygBvKCkaFXNQRz8du0bhnotgxiXZ5G++nt+7Pd5jAxdcYvrn4naxJ0yhaEeZ3kSGkRxovNX9MN7/UkFEW+titwXqtRFY6KUXBec8ZQdPHFY+HKPqxHg+BLslaT8nk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
